spring: 
  profiles: 
    active: 
      -dev
---
spring: 
  profiles: dev
  application: 
    name: microservice-config-kingsware-dev
---
spring: 
  profiles: test
  application: 
    name: microservice-config-kingsware-test